apiVersion: v1
kind: Service
metadata:
  name: i2037-webapp
  labels:
    app: i2037
    tier: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: i2037
    tier: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: i2037-webapp
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: i2037
        tier: web
    spec:
      containers:
      - name: i2037-webapp
        image: i2037-webapp:1.0.3
        env:
        - name: I2037_DB_HOST
          value: i2037-db
        - name: I2037_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: i2037-db-pass
              key: password
        ports:
        - containerPort: 8080
