apiVersion: v1
kind: PersistentVolume
metadata:
  name: i2037-pv1
  labels:
    app: i2037
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: i2037-db-disk
    fsType: ext4