kind: PersistentVolume
apiVersion: v1
metadata:
  name: i2037-pv1
  labels:
    app: i2037
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/i2037-pv1"