apiVersion: v1
kind: Service
metadata:
  name: i2037-webapp
  labels:
    app: i2037
    tier: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: i2037
    tier: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: i2037-webapp
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: i2037
        tier: web
    spec:
      containers:
      - name: i2037-webapp
        image: __IMAGE__
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: I2037_PASSWORD_SALT
          valueFrom:
            secretKeyRef:
              name: i2037-webapp-salt
              key: salt
        - name: I2037_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: i2037-db-user-pass
              key: password
        - name: I2037_HOME
          value: /var/lib/i2037
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /var/lib/i2037/etc
      volumes:
      - name: config-volume
        configMap:
          name: i2037-config
