kind: PersistentVolume
apiVersion: v1
metadata:
  name: i2037-pv1
  annotations:
    pv.beta.kubernetes.io/gid: "1200"  
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/var/i2037-pv1"